name: HW2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.3
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - contextily
  - rasterio
  - scipy
  - cartopy
  - xarray
  - openblas==0.2.19
  - netcdf4==1.5.1
  - pystac-client
  - planetary-computer
  - geopandas
  - rich
